import type { Colleague, Room } from './types'

const brandAsset = (file: string) => `${import.meta.env.BASE_URL}brand/${file}`

export const colleagues: Colleague[] = [
  {
    id: 'mira',
    name: 'Mira',
    role: 'Cognitive Product Architect',
    protects: 'The human problem',
    question: 'What are we actually trying to change?',
    contribution: 'Frames intent, the human task, desired progress, and success before anyone begins building.',
    accent: '#0e5a5a',
    image: brandAsset('character-1.png'),
    phase: 'frame',
  },
  {
    id: 'echo',
    name: 'Echo',
    role: 'Evidence & Learning',
    protects: 'What the Company knows',
    question: 'What supports that?',
    contribution: 'Separates sources, observations, assumptions, confidence, unknowns, and corrective learning.',
    accent: '#9a6b13',
    image: brandAsset('character-5.png'),
    phase: 'evidence',
  },
  {
    id: 'rook',
    name: 'Rook',
    role: 'Independent Product Critic',
    protects: 'The Company from its own confidence',
    question: 'What are we assuming?',
    contribution: 'Challenges unsupported claims, hidden failure modes, unsafe automation, and unnecessary scope.',
    accent: '#7d2b2b',
    image: brandAsset('character-3.png'),
    phase: 'decide',
  },
  {
    id: 'atlas',
    name: 'Atlas',
    role: 'Systems Architect',
    protects: 'Structural integrity',
    question: 'What has to be true for this to work reliably?',
    contribution: 'Translates approved product reasoning into entities, states, permissions, and recovery paths.',
    accent: '#245a7a',
    image: brandAsset('character-2.png'),
    phase: 'decide',
  },
  {
    id: 'forge',
    name: 'Forge',
    role: 'Builder',
    protects: 'Execution',
    question: 'What exactly are we building?',
    contribution: 'Turns approved scope into testable work and escalates product, risk, or irreversible changes.',
    accent: '#9d541b',
    image: brandAsset('character-4.png'),
    phase: 'learn',
  },
  {
    id: 'nexus',
    name: 'Nexus',
    role: 'Team Coordinator',
    protects: 'Coordinated responsibility',
    question: 'Who needs to be in the room next?',
    contribution: 'Maintains responsibility, handoffs, approval gates, and the next valid owner throughout the Room.',
    accent: '#5d3a6f',
    image: brandAsset('character-6.png'),
    phase: 'frame',
  },
]

const createdAt = '2026-08-13T18:00:00-05:00'

export const seedRoom: Room = {
  id: 'good-company-v01',
  title: 'Good Company V0.1',
  intent: 'Turn Cognitive Product Engineering into a working, evidence-backed product experience.',
  human: 'A founder or product operator using AI to turn ambiguous work into a decision and build.',
  desiredProgress: 'Move from an idea to an approved, testable product contract without losing evidence, responsibility, or learning.',
  success: 'A user can open a Room, frame the work, inspect evidence and assumptions, approve a direction, and record what happened.',
  phase: 'frame',
  evidence: [
    {
      id: 'evidence-product-definition',
      statement: 'The product must connect human cognition, evidence, decisions, controlled execution, verification, and learning.',
      source: 'Cognitive Product Engineering Product Definition V0.1',
      type: 'source',
      confidence: 'high',
      createdAt,
    },
    {
      id: 'evidence-dtg-pattern',
      statement: 'Evidence-backed recommendations become more useful when they create explicit operational states and preserve provenance.',
      source: 'Observed pattern from the DTG operator architecture',
      type: 'observation',
      confidence: 'medium',
      createdAt,
    },
    {
      id: 'assumption-colleagues',
      statement: 'Founders will understand specialized responsibility more easily through visible colleagues than through one opaque assistant.',
      source: 'Good Company product hypothesis',
      type: 'assumption',
      confidence: 'low',
      createdAt,
    },
  ],
  recommendation: null,
  decision: null,
  approved: false,
  approvalNote: '',
  outcome: '',
  learning: '',
  createdAt,
  updatedAt: createdAt,
  history: [
    {
      id: 'history-opened',
      type: 'room',
      title: 'Room opened',
      detail: 'Good Company V0.1 entered framing with the founding Company present.',
      createdAt,
    },
  ],
}
